Application.URL=https://practice.expandtesting.com/notes/app
API.Base.URL=https://practice.expandtesting.com/notes/api
Browser=Chrome
Environment=QA
Framework=Selenium 4 + RestAssured + TestNG
Java.Version=11
Test.User=omgdongare@gmail.com
